Repository 1408Hyper/2024HighStakesCode, pull requests merged in 2024-10, with the labels that each got.

#5 Add components and overhaul code
  .github/workflows/c-cpp.yml
  include/antitheft.h
  include/main.h
  include/options.h
  project.pros
  src/main.cpp
Labels: bug, enhancement, high-priority

#13 Refactor classes & AbstractMech
  include/options.h
  src/main.cpp
Labels: enhancement, high-priority

#12 Troubleshooting gcc attempt #4
  .github/workflows/c-cpp.yml
  scripts/install-arm-gcc.sh
Labels: bug, help wanted, question, medium-priority

#16 Overhauling drivetrain component with opcontrol
  README.md
  include/fmt/base.h
  include/fmt/format-inl.h
  include/fmt/format.h
  include/main.h
  include/options.h
  src/main.cpp
Labels: bug, enhancement, high-priority

#17 AbstractMG, Intake and BiToggle
  include/options.h
  src/main.cpp
Labels: enhancement, high-priority
